### ISSUE TITLE
OTA function broken

### ISSUE THREAD

**Issue by pasyn** [ProtonAOSP/android_device_google_wahoo#4]
See screenshot of update menu

![Screenshot_20210712-234514_Google_Play_services.png](https://user-images.githubusercontent.com/67178218/125387637-39c33680-e36c-11eb-96bf-53c87a3dda60.png)

**Comment by kdrag0n** [comment]
ProtonAOSP doesn't have support for OTA updates. That's the stock updater provided by Google Play Services, which won't work properly on ProtonAOSP.
